apiVersion: v1
kind: Pod
metadata:
  name: django
  labels:
    function: djangosite
spec:
  containers:
  - name: django
    image: ghcr.io/connormunger/cis-92:milestone-5.0
    ports:
    - containerPort: 8080
    env:
    - name: SECRET_KEY
      value: 'keyvalue'
    - name: DB_NAME
      value: mysite
    - name: DB_USER
      value: postgres
    - name: DB_PASSWORD
      value: django
    - name: DB_HOST
      value: postgres
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8080