apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: djangosite
spec:
  containers:
  - name: django
    image: ghcr.io/connormunger/cis-92:milestone-4.4
    ports:
    - containerPort: 8080
    env:
    - name: SECRET_KEY
      value: 'keyvalue'